"use strict";

//DB
const mongoose = require("mongoose");
const { Schema } = mongoose;

const OfertaSchema = new Schema({
  candidatos: [{ type: Schema.Types.ObjectId, ref: "Candidato" }],
  descripcion: { type: String },
  titulo: { type: String },
  salario: {
    type: Number,
    validate: {
      validator: Number.isInteger,
      message: "{VALUE} no es un numero",
    },
  },
  puesto: { type: String },
  sector: { type: String },
  empresa: { type: Schema.Types.ObjectId, ref: "Empresa", required: true },
  provincia: {
    type: String,
    enum: [
      "A Coruña",
      "Álava",
      "Albacete",
      "Alicante",
      "Almería",
      "Asturias",
      "Ávila",
      "Badajoz",
      "Baleares",
      "Barcelona",
      "Burgos",
      "Cáceres",
      "Cádiz",
      "Cantabria",
      "Castellón",
      "Ciudad Real",
      "Córdoba",
      "Cuenca",
      "Girona",
      "Granada",
      "Guadalajara",
      "Gipuzkoa",
      "Huelva",
      "Huesca",
      "Jaén",
      "La Rioja",
      "Las Palmas",
      "León",
      "Lérida",
      "Lugo",
      "Madrid",
      "Málaga",
      "Murcia",
      "Navarra",
      "Ourense",
      "Palencia",
      "Pontevedra",
      "Salamanca",
      "Segovia",
      "Sevilla",
      "Soria",
      "Tarragona",
      "Santa Cruz de Tenerife",
      "Teruel",
      "Toledo",
      "Valencia",
      "Valladolid",
      "Vizcaya",
      "Zamora",
      "Zaragoza",
    ],
    required: true,
  },
});

module.exports = mongoose.model("Oferta", OfertaSchema);
